experiment:
  seed: 28
  num_epochs: 25
  batch_size: 128

model:
  cae:
    from_module: cae
    encoder_class_name: Autoencoder
    encoder_name: cae
    args: []
    kwargs:
      in_channels: 6
      max_len: 20

      kernel_size: 3
      out_channels: [4, 8, 16]
      latent_size: 64
      
      lr: 0.001
      optimizer_name: "adam"